### PR TITLE
Python 3 port.

### PR DESCRIPTION
**Pull request by F483**
I have ported almost all the code to python 3 (including readme and examples) as you can see on Travis.

Not all examples work yet and compatibility still need to be verified between the older python 2 version and the ported version. Also I do not know nosetests to well and am not sure why the coverage results are not being posted to http://coveralls.io/

I have an upstream library that I need working with python 3 and this is the last package I need to port (I ported your bunch dependence already), any help would be greatly appreciated.

### CODE REVIEW

**Comment by femtotrader** [comment]
Thanks for your work but a discussion about https://github.com/F483/neobunch/issues/2 will be great.

**Comment by F483** [comment]
I will take a look at Munch and merge the two projects if I can. For python-jsonrpc it should be irreverent which one is used.

**Comment by gerold-penz** [comment]
Hi F483!
You have done great work. But I may not merge code which I can't maintain. In my live, I have not wrote one line of Python 3 code. Sorry!
Please create your own fork or whatever. The name "python3-jsonrpc" is free in PyPi.
Regards

**Comment by F483** [comment]
The difference between python 2 and 3 are minimal and would also help maintain it as I would also be dependant on it.

**Comment by scls19fr** [comment]
Maybe we can be more constructive. Create an organization...

**Pull request closed without merging**
