### PR TITLE
Added badges to README & Python version to Travis

### PR DESCRIPTION
**Pull request by ZuluPro**
- Added coverage
- Added PyPy to travis matrix
- Added badges about CI

For enable coverage badge you must subscribe to Coveralls.io

### CODE REVIEW

**Comment by ZuluPro** [comment]
Any news ?

**Comment by ZuluPro** [comment]
@gerold-penz Any news ?

**Comment by ZuluPro** [comment]
@gerold-penz Any news ?

**Comment by gerold-penz** [comment]
Hi ZuluPro! Thanks for your effort.

**Pull request merged**
