### PR TITLE
Add a first nosetests test

### PR DESCRIPTION
**Pull request by scls19fr**

### CODE REVIEW

**Comment by scls19fr** [comment]
You just need to run it using

    $ nosetests -s -v

to ensure that it's working fine

**Comment by scls19fr** [comment]
see https://github.com/gerold-penz/python-jsonrpc/issues/28

**Comment by scls19fr** [comment]
You might also enable Travis
https://travis-ci.org/gerold-penz/python-jsonrpc

and add a badge to README.rst

.. image:: https://travis-ci.org/gerold-penz/python-jsonrpc.svg?branch=master
    :target: https://travis-ci.org/gerold-penz/python-jsonrpc

**Comment by gerold-penz** [comment]
Thank you! I'll do it.

**Pull request merged**
