### PR TITLE
Option to pass custom ssl context.

### PR DESCRIPTION
**Pull request by chris-barry**
See #21. I tested it, supplied doumentation, and even an example. Let me know what else would have to be done to get this merged.

Thanks for making an easy to understand library :smile:

### CODE REVIEW

**Comment by chris-barry** [comment]
Edited to also include a fix for #23.

**Comment by chris-barry** [comment]
Any chance of getting this merged? :smile:

**Comment by gerold-penz** [comment]
Hi chris-barry! The chance is very good. But I'm on vacation. Next weeks, I'll take care of it.

**Comment by chris-barry** [comment]
Very sorry to pester you on your vacation. Have a good time!

**Comment by gerold-penz** [comment]
done

**Pull request closed without merging**
